// <auto-generated />
using System;
using ArtikullServices.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtikullServices.Migrations
{
    [DbContext(typeof(ArtikullServicesDbContext))]
    partial class ArtikullServicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArtikullServices.Models.Produkt", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("BarkodKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Cmimi")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataSkadences")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emertimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KaTvsh")
                        .HasColumnType("bit");

                    b.Property<int>("Lloj")
                        .HasColumnType("int");

                    b.Property<string>("Njesia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipi")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("cases");
                });
#pragma warning restore 612, 618
        }
    }
}
